
// This file was generated by Firebase Studio
import { initializeApp, getApps, getApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {
  "projectId": "africa-heal-health-x8xrn",
  "appId": "1:1045454466664:web:6670104342f19a293915dd",
  "storageBucket": "africa-heal-health-x8xrn.firebasestorage.app",
  "apiKey": "AIzaSyBneaW2qiPeFUuUzK6MpsSEQS3JGc3dAYA",
  "authDomain": "africa-heal-health-x8xrn.firebaseapp.com",
  "messagingSenderId": "1045454466664"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);

export { app, auth, db };
