
import type { Product } from "@/lib/types"

export const products: Product[] = [
  {
    id: "CC01",
    name: "Digital Blood Pressure Monitor",
    description: "Easy-to-use automatic wrist blood pressure monitor for reliable tracking of your cardiovascular health at home.",
    price: 4500,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "blood pressure monitor",
    category: "Chronic Care",
    brand: "MediTech",
    tags: ["featured", "health monitoring"],
  },
  {
    id: "CC02",
    name: "Portable Nebulizer",
    description: "Compact and silent mesh nebulizer for respiratory treatments, ideal for managing asthma or COPD on the go.",
    price: 7800,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "portable nebulizer",
    category: "Chronic Care",
    brand: "Respira",
    tags: ["respiratory"],
  },
  {
    id: "CC03",
    name: "Smart Pill Organizer",
    description: "An electronic pill box with reminders and tracking to ensure you never miss a dose of your vital medication.",
    price: 3200,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "pill organizer",
    category: "Chronic Care",
    brand: "PharmaCare",
    tags: ["medication management"],
  },
  {
    id: "ER01",
    name: "Advanced First-Aid Kit",
    description: "Comprehensive 150-piece first-aid kit designed for handling common injuries and minor emergencies.",
    price: 5500,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "first aid kit",
    category: "Emergency Response",
    brand: "RescueReady",
    tags: ["featured", "emergency"],
  },
  {
    id: "ER02",
    name: "Emergency Tourniquet",
    description: "A military-grade combat application tourniquet for rapid, one-handed application to stop severe bleeding.",
    price: 2500,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "medical tourniquet",
    category: "Emergency Response",
    brand: "RescueReady",
    tags: ["trauma care"],
  },
  {
    id: "ER03",
    name: "Personal CPR Face Shield",
    description: "A compact, single-use CPR mask with a one-way valve, essential for any emergency kit.",
    price: 500,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "cpr mask",
    category: "Emergency Response",
    brand: "RescueReady",
    tags: ["safety"],
  },
  {
    id: "MT01",
    name: "Medical Travel Insurance Plan",
    description: "Specialized travel insurance covering medical emergencies, trip cancellations, and complications during medical tourism.",
    price: 15000,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "travel insurance document",
    category: "Medical Tourism",
    brand: "GlobalGuard",
    tags: ["travel"],
  },
  {
    id: "MT02",
    name: "Compression Socks for Travel",
    description: "High-quality compression stockings to improve circulation and reduce the risk of DVT during long flights.",
    price: 2800,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "compression socks",
    category: "Medical Tourism",
    brand: "MediTech",
    tags: ["travel", "comfort"],
  },
  {
    id: "OT01",
    name: "Post-Transplant Care Package",
    description: "A curated package including immunosuppressant medication organizers, sterile wound care supplies, and health monitoring tools.",
    price: 12500,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "medical care package",
    category: "Organ Transplants",
    brand: "PharmaCare",
    tags: ["featured", "post-op"],
  },
  {
    id: "OT02",
    name: "Tacrolimus (Immunosuppressant)",
    description: "Prescription medication to prevent organ rejection after a transplant. Requires a valid prescription.",
    price: 9800,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "prescription medicine bottle",
    category: "Organ Transplants",
    brand: "PharmaCare",
    tags: ["prescription"],
  },
  {
    id: "CC04",
    name: "Insulin Cooling Travel Case",
    description: "A portable, temperature-controlled case for safely transporting insulin and other temperature-sensitive medications.",
    price: 4200,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "insulin travel case",
    category: "Chronic Care",
    brand: "MediTech",
    tags: ["diabetes", "travel"],
  },
  {
    id: "CC05",
    name: "Cholesterol Test Strips (50 ct.)",
    description: "High-accuracy test strips for use with digital cholesterol monitors. Provides fast results for total cholesterol.",
    price: 3500,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "test strips box",
    category: "Chronic Care",
    brand: "MediHealth",
    tags: ["health monitoring"],
  }
];

export const getBrands = () => [...new Set(products.map(p => p.brand))];
export const getCategories = () => [...new Set(products.map(p => p.category))];
export const getMaxPrice = () => Math.max(...products.map(p => p.price));
