import type { Product } from "@/lib/types"

export const products: Product[] = [
  {
    id: "1",
    name: "Moringa Powder",
    description: "A nutrient-packed superfood, rich in vitamins and antioxidants. Ideal for boosting energy and overall wellness.",
    price: 15.99,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "supplement powder",
    category: "Superfoods",
    featured: true,
  },
  {
    id: "2",
    name: "Baobab Fruit Powder",
    description: "Excellent source of Vitamin C, fiber, and antioxidants. Supports immune function and digestive health.",
    price: 18.50,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "fruit powder",
    category: "Superfoods",
    featured: true,
  },
  {
    id: "3",
    name: "African Black Soap",
    description: "Traditional, all-natural soap for face and body. Known for its cleansing and clarifying properties.",
    price: 8.99,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "natural soap",
    category: "Skincare",
    featured: true,
  },
  {
    id: "4",
    name: "Shea Butter",
    description: "Raw, unrefined shea butter for deep moisturization. Perfect for skin and hair.",
    price: 12.00,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "shea butter",
    category: "Skincare",
  },
  {
    id: "5",
    name: "Hibiscus Tea",
    description: "A refreshing herbal tea packed with antioxidants. Helps support cardiovascular health.",
    price: 7.50,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "herbal tea",
    category: "Beverages",
    featured: true,
  },
  {
    id: "6",
    name: "Fonio Grain",
    description: "A gluten-free, ancient grain that is a nutritious alternative to quinoa or rice. Rich in amino acids.",
    price: 9.99,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "ancient grain",
    category: "Grains",
  },
  {
    id: "7",
    name: "Rooibos Tea",
    description: "Caffeine-free red tea from South Africa. Known for its calming properties and rich antioxidant content.",
    price: 8.00,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "herbal tea",
    category: "Beverages",
  },
  {
    id: "8",
    name: "Marula Oil",
    description: "A lightweight, hydrating oil for skin and hair. Rich in antioxidants and essential fatty acids.",
    price: 25.00,
    image: "https://placehold.co/600x400.png",
    dataAiHint: "beauty oil",
    category: "Skincare",
  },
];
